#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#User
user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [POST,GET]

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

#Invoice
invoice:
    path: /invoice
    controller: App\Controller\InvoiceController::index
    methods: [POST]
