#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#User
user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [POST,GET]

#Invoice
invoice:
    path: /invoice
    controller: App\Controller\InvoiceController::index
    methods: [POST]
