#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#User
user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [POST,GET]

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

#Invoice
invoice:
    path: /invoice
    controller: App\Controller\InvoiceController::index
    methods: [POST]
